"""Add bot configuration table

Revision ID: 343c78c7a0b8
Revises: layout
Create Date: 2018-02-23 10:06:09.766820+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '343c78c7a0b8'
down_revision = 'layout'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.alter_column('playback', 'start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('playback', 'track_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('track', 'extid',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('track', 'length',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('track', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('track', 'origin',
               existing_type=postgresql.ENUM('youtube', 'soundcloud', name='origin'),
               nullable=False)
    op.alter_column('user', 'dtid',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('user_action', 'action',
               existing_type=postgresql.ENUM('skip', 'upvote', 'downvote', name='action'),
               nullable=False)
    op.alter_column('user_action', 'playback_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_action', 'ts',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_action', 'ts',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_action', 'playback_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_action', 'action',
               existing_type=postgresql.ENUM('skip', 'upvote', 'downvote', name='action'),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('user', 'dtid',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('track', 'origin',
               existing_type=postgresql.ENUM('youtube', 'soundcloud', name='origin'),
               nullable=True)
    op.alter_column('track', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('track', 'length',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('track', 'extid',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('playback', 'track_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('playback', 'start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_table('bot_data')
    # ### end Alembic commands ###
